name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v2
      - name: Publish
        run: |
          VERSION_TAG=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo NEW_VERSION="${VERSION_TAG:1}" >> $GITHUB_ENV
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} >> .npmrc
          bun install
          bun run build
          cd src
          pnpm version $NEW_VERSION
          pnpm publish --no-git-checks
